apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp1
  name: myapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  strategy:
    rollingUpdate:
      maxSurge: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: myapp1-configmap
            - secretRef:
                name: myapp1-secret
          image: bhanujggandhi/myapp1:latest
          name: myapp1
          ports:
            - containerPort: 5000
